spring:
  config:
    import: application-secret.properties
  datasource:
    hikari:
      data:
        jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
        username: sa
        password:
        driver-class-name: org.h2.Driver
      dev:
        jdbc-url: jdbc:h2:mem:testdb2;MODE=MYSQL
        username: sa
        password:
        driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        use_sql_comments: true
        generate_statistics: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
