spring:
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

jwt:
  secret: ${JWT_SECRET}
  time:
    access: ${JWT_ACCESS}
    refresh: ${JWT_REFRESH}

# Scheduler
schedule:
  cron:
  use: true

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.tenten.eatmatjib.data.pipeline