CREATE TABLE IF NOT EXISTS raw_restaurant
(
    id                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    opnsfteamcode       VARCHAR(255)       NULL,
    mgtno               VARCHAR(255)       NULL,
    apvpermymd          VARCHAR(255)       NULL,
    apvcancelymd        VARCHAR(255)       NULL,
    trdstategbn         VARCHAR(255)       NULL,
    trdstatenm          VARCHAR(255)       NULL,
    dtlstategbn         VARCHAR(255)       NULL,
    dtlstatenm          VARCHAR(255)       NULL,
    dcbymd              VARCHAR(255)       NULL,
    clgstdt             VARCHAR(255)       NULL,
    clgenddt            VARCHAR(255)       NULL,
    ropnymd             VARCHAR(255)       NULL,
    sitetel             VARCHAR(255)       NULL,
    sitearea            VARCHAR(255)       NULL,
    sitepostno          VARCHAR(255)       NULL,
    sitewhladdr         VARCHAR(255)       NULL,
    rdnwhladdr          VARCHAR(255)       NULL,
    rdnpostno           VARCHAR(255)       NULL,
    bplcnm              VARCHAR(255)       NULL,
    lastmodts           VARCHAR(255)       NULL,
    updategbn           VARCHAR(255)       NULL,
    updatedt            VARCHAR(255)       NULL,
    uptaenm             VARCHAR(255)       NULL,
    x                   VARCHAR(255)       NULL,
    y                   VARCHAR(255)       NULL,
    sntuptaenm          VARCHAR(255)       NULL,
    maneipcnt           VARCHAR(255)       NULL,
    wmeipcnt            VARCHAR(255)       NULL,
    trdpjubnsenm        VARCHAR(255)       NULL,
    lvsenm              VARCHAR(255)       NULL,
    wtrsplyfacilsenm    VARCHAR(255)       NULL,
    totepnum            VARCHAR(255)       NULL,
    hoffepcnt           VARCHAR(255)       NULL,
    fctyowkepcnt        VARCHAR(255)       NULL,
    fctysiljobepcnt     VARCHAR(255)       NULL,
    fctypdtjobepcnt     VARCHAR(255)       NULL,
    bdngownsenm         VARCHAR(255)       NULL,
    isream              VARCHAR(255)       NULL,
    monam               VARCHAR(255)       NULL,
    multusnupsoyn       VARCHAR(255)       NULL,
    faciltotscp         VARCHAR(255)       NULL,
    jtupsoasgnno        VARCHAR(255)       NULL,
    jtupsomainedf       VARCHAR(255)       NULL,
    homepage            VARCHAR(255)       NULL,
    is_updated          TINYINT(1)         NOT NULL
);